# Generated by Django 4.0.3 on 2022-03-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_alter_post_author_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Aragorn', on_delete=django.db.models.deletion.CASCADE, to='newapp.author', verbose_name='Автор (author)'),
        ),
    ]
